# User Api

### Register user1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "email": "user1@example.com",
    "username": "user1",
    "password": "user1"
  }
}

> {%
    client.global.set("token", response.body.user.token)
%}

### Register user2
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "email": "user2@example.com",
    "username": "user2",
    "password": "user2"
  }
}

> {%
    client.global.set("token", response.body.user.token)
%}

### Login user1
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "user1@example.com",
    "password": "user1"
  }
}

> {%
    client.global.set("token", response.body.user.token)
%}

### Current user
GET http://localhost:8080/api/user
Authorization: Token {{token}}

### Update User
PUT http://localhost:8080/api/user
Authorization: Token {{token}}
Content-Type: application/json

{
  "user": {}
}

###

# Profile Api

### Get profile
GET http://localhost:8080/api/profiles/user1
Authorization: Token {{token}}

### Follow profile
POST http://localhost:8080/api/profiles/user1/follow
Authorization: {{token}}

### Unfollow profile
DELETE http://localhost:8080/api/profiles/user1/follow
Authorization: Token {{token}}

###

# Article Api

### Feed articles
GET http://localhost:8080/api/articles/feed?
    offset=0&
    limit=100
Authorization: Token {{token}}

### Filter articles
GET http://localhost:8080/api/articles?
    tag=&
    author=&
    favorited=&
    offset=0&
    limit=100

### Create article
POST http://localhost:8080/api/articles
Authorization: {{token}}
Content-Type: application/json

{
  "article": {
    "title": "art2",
    "description": "art1",
    "body": "art1",
    "tagList": ["qwer", "asdf"]
  }
}

### Get article
GET http://localhost:8080/api/articles/art2

### Update article
PUT http://localhost:8080/api/articles/art2
Content-Type: application/json

{
  "article": {}
}

### Delete article
DELETE http://localhost:8080/api/articles/art2
Authorization: Token {{token}}

### List comments
GET http://localhost:8080/api/articles/art2/comments

### Add comment
POST http://localhost:8080/api/articles/art2/comments
Authorization: Token {{token}}
Content-Type: application/json

{
  "comment": {
    "body": "qwer"
  }
}

### Delete comment
DELETE http://localhost:8080/api/articles/art2/comments/1

### Favorite article
POST http://localhost:8080/api/articles/art2/favorite
Authorization: Token {{token}}

### Unfavorite article
DELETE http://localhost:8080/api/articles/art2/favorite

###

# Tags Api

### List tags
GET http://localhost:8080/api/tags