spring.application.name=realworld-backend-spring
spring.h2.console.enabled=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

management.endpoints.web.exposure.include=info,health,prometheus,startup
#management.endpoint.health.group.qwer.exclude=asdf
#management.endpoint.health.exclude=asdf
#management.endpoint.health.group.qwer.exclude=asdf
management.endpoint.health.show-details=always
management.endpoint.health.group.readiness.show-components=always
management.endpoint.health.group.readiness.show-details=always
#management.endpoint.health.group.readiness.exclude=db/secondaryDataSource

springdoc.show-actuator=true
springdoc.swagger-ui.operationsSorter=alpha

api.version=/api